### ISSUE TITLE
Flask_Restplus is abandoned, replace with Flask_Restx?

### ISSUE THREAD

**Issue by vaustrup** [dusktreader/flask-buzz#26]
Flask_Restplus has not been updated in quite some time and seems to have been forked into Flask_Restx, which is actively developed, see [the docs here](https://flask-restx.readthedocs.io/en/latest/). The dependency should probably be replaced. I would be happy to create a PR for this, if you agree.

**Comment by dusktreader** [comment]
Yeah, that sounds fine to me. I would welcome the pull-request

**Comment by vaustrup** [comment]
Great, I've created the PR. Let me know what you think.

**Comment by dusktreader** [comment]
This has been resolved by PR #27 

I've also updated the version to 2.0.0 (due to breaking change) and published to pypi.

Thanks for the contribution!
